call plug#begin('~/.vim/plugged')
" Auto completer
Plug 'Valloric/YouCompleteMe', { 'do': './install.py --clang-completer --cs-completer --ts-completer --rust-completer' }
" A bar showing ctags
Plug 'majutsushi/tagbar'
" clang-format support
Plug 'rhysd/vim-clang-format'
" Fuzzy finder
Plug 'ctrlpvim/ctrlp.vim'
" Multiple Cursor support
Plug 'terryma/vim-multiple-cursors'
" Useful Utility Commands
Plug 'tpope/vim-eunuch'
" File browser
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
" Support .editerconfig
Plug 'editorconfig/editorconfig-vim'
" HTML Tags Input Helper
Plug 'mattn/emmet-vim'
" Normal Mode Parentheses Add/Modify/Delete
Plug 'tpope/vim-surround'
" Auto Pair Parentheses
Plug 'jiangmiao/auto-pairs'
" Better '*' searching
Plug 'bronson/vim-visual-star-search'
" Switching between single-line and multi-line
Plug 'AndrewRadev/splitjoin.vim'
" Git Commands
Plug 'tpope/vim-fugitive'
" Git diff showing
Plug 'airblade/vim-gitgutter'
" Scrolling Animating
Plug 'yuttie/comfortable-motion.vim'
" Airline Appearance
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Tender theme
Plug 'jacoborus/tender.vim'
" Better tmux integration
Plug 'tmux-plugins/vim-tmux-focus-events'
call plug#end()

syntax on
set number
set t_Co=256
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set cursorline
set noeb
set background=dark
set enc=utf8
set mouse=a
set ic
set hls
set hlsearch
set history=50
set ai
set laststatus=2
set showtabline=2
set updatetime=1000
set pastetoggle=<F10>
set clipboard=unnamedplus

nmap <F7> :TagbarToggle<CR>
nmap <F8> :NERDTreeToggle<CR>
nmap <F9> :GitGutterToggle<CR>

let mapleader = ' '
nnoremap <silent> <Leader>w :w<CR>
nnoremap <silent> <Leader>W :w!<CR>
nnoremap <silent> <Leader>x :wq<CR>
nnoremap <silent> <Leader>q :q<CR>
nnoremap <silent> <Leader>p :CtrlPTag<CR>
autocmd FileType c,cpp,objc nnoremap <silent> <Leader>f :ClangFormat<CR>

if (has("termguicolors"))
 set termguicolors
endif

filetype indent on
colorscheme tender

let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0 
let g:ycm_warning_symbol = '->'

let g:gitgutter_max_signs = 1000

"let g:AutoPairsFlyMode = 1
let g:AutoPairsMapBS = 0

let g:tagbar_autofocus = 1
let g:tagbar_autoshowtag = 1

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#ycm#enabled = 1
let g:airline_theme = 'tender'

let g:clang_format#detect_style_file = 1
let g:clang_format#auto_format = 0
let g:clang_format#auto_format_on_insert_leave = 0

command Cpp11 execute "!g++ -lm -lcrypt -O2 -std=c++11 -o " . expand('%:r') . " " . @%
command Cansi execute "!gcc -lm -lcrypt -O2 -ansi -o " . expand('%:r') . " " . @%
command Reload execute ":source $MYVIMRC"

