alias ls='ls --color=auto'
alias lp='ls -l -a'
alias la='ls -a'
alias ll='ls -l'
alias ds='dirs -p -v'
alias cp='cp -i'
alias mv='mv -i'
alias cpp='cp -pi'
alias cpa='cp -a'
alias cpr='cp -R'
alias storls='ll /dev/sd*'
